"""Dashboard page UI."""

from __future__ import annotations

import streamlit as st

from services.patient_service import load_dashboard_registry
from services.runtime import get_registered_trials
from services.trial_format import format_trial_exclusions_html, format_trial_inclusion_html
from ui.components import (
    _esc,
    clinical_panel,
    render_architecture_flow,
    render_clinical_notice,
    render_feature_grid,
    render_page_header,
    render_section,
    render_status_metric,
)
from ui.pages._common import clear_cache_if_needed, data_source_label, get_patient_provider

def _render_note_preview(patients, *, n: int = 3) -> None:
    samples = [p for p in patients if getattr(p, "ehr_note", "")][:n]
    if not samples:
        render_clinical_notice(
            "No synthesised notes available — active provider did not stamp ehr_note.",
            "INCONCLUSIVE",
        )
        return

    st.caption(
        "Each note is generated by `data_loader.generate_mock_clinical_note()` "
        "and passed to BioBERT during Patient Matching."
    )
    for profile in samples:
        st.markdown(
            f"`{profile.patient_id}` · {profile.data_source} · "
            f"age {profile.age or 'unknown'} · {profile.gender or 'unknown'} · "
            f"{len(profile.active_conditions)} condition(s) · "
            f"{len(profile.medications)} medication(s)"
        )
        st.markdown(
            f'<div style="padding:.65rem .85rem;border-radius:.5rem;'
            f'background:var(--surface);border-left:4px solid var(--brand);'
            f'font-family:ui-monospace,Consolas,monospace;font-size:.82rem;'
            f'line-height:1.45;color:var(--text-primary);margin-bottom:.6rem;">'
            f"{profile.ehr_note}</div>",
            unsafe_allow_html=True,
        )

def _render_overview(trial_count: int, patient_count: int) -> None:
    with clinical_panel("Platform Overview"):
        k1, k2, k3, k4 = st.columns(4)
        with k1:
            render_status_metric("Registered Trials", str(trial_count), "NEUTRAL")
        with k2:
            render_status_metric("Patient Profiles", str(patient_count), "NEUTRAL")
        with k3:
            render_status_metric("Pipeline Stages", "5", "PASS")
        with k4:
            render_status_metric("Evaluation Suite", "P / R / F1", "INCONCLUSIVE")

def _render_trial_registry(trials: list) -> None:
    render_section("Trial Registry")
    st.caption(
        f"{len(trials)} protocol(s) loaded from trials/ — add a JSON file and restart "
        "the app to register a new trial."
    )
    with clinical_panel("Registered Protocols"):
        for trial in trials:
            inclusion = trial.get("inclusion") or {}
            exclusion = trial.get("exclusion") or {}
            st.markdown(
                f'<div class="trial-table-row">'
                f'<div class="trial-table-id">{_esc(trial["trial_id"])}</div>'
                f'<div class="trial-table-main">'
                f'<strong>{_esc(trial["trial_name"])}</strong>'
                f'<div class="trial-table-inc">{format_trial_inclusion_html(inclusion)}</div>'
                f'</div>'
                f'<div class="trial-table-excl">{format_trial_exclusions_html(exclusion)}</div>'
                f'</div>',
                unsafe_allow_html=True,
            )

def page_dashboard() -> None:
    render_page_header(
        "System Overview",
        "Clinical Trial Matching Platform",
        "Neuro-symbolic pipeline combining BioBERT entity extraction with "
        "deterministic eligibility validation and explainable audit reports.",
        chips=[("BioBERT Active", True), ("Symbolic Rules", False), ("Dual XAI", False)],
    )

    trials = get_registered_trials()
    clear_cache_if_needed()
    registry, patients, source_label = load_dashboard_registry(get_patient_provider)

    _render_overview(len(trials), len(patients))

    render_section("Synthesised Clinical Notes (BioBERT Input)")
    with clinical_panel(f"Sample free-text notes generated from {data_source_label()}"):
        if registry is None:
            render_clinical_notice(
                "Patient registry not loaded — fix the data source path to preview notes.",
                "FAIL",
            )
        else:
            _render_note_preview(patients, n=3)

    render_section("System Architecture")
    with clinical_panel():
        render_architecture_flow()

    render_section("Core Capabilities")
    with clinical_panel():
        render_feature_grid()

    _render_trial_registry(trials)

    render_clinical_notice(
        f"Research prototype loading patients from local CSV ({source_label}). "
        "All outputs require clinician review before any clinical action.",
        "INCONCLUSIVE",
    )
